---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

# Scrape with my Home Assistant instance
  - job_name: 'home_assistant'
    static_configs:
      - targets: ['192.168.1.20:8123']
        labels:
          instance: 'home_assistant'
    authorization:
      credentials: |
        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI5Yjc5N2E0MmE4ODc0MTQxYTM4YmY1ZTA5MjA2OTJjMyIsImlhdCI6MTc1MTI4NzIxNiwiZXhwIjoyMDY2NjQ3MjE2fQ.k3cXG5P9DffNaDJcoRVayCNoTooh4NPPvnTPQE0Snyk
      