---
name: Simulated HA Install

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Simulate HA install script
        run: |
          echo "🚧 Simulating HA install script (no Docker in GitHub CI)"
          bash lxc-setup/install_ha_docker.sh || \
          echo "Script partially run for simulation."
        shell: bash
